name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install rustup
      run: rustup target add x86_64-unknown-uefi
    - name: Install rustup x2
      run: rustup target add x86_64-unknown-none
    - name: Build bootloader
      run: make build-bootloader
    - name: Build kernel
      run: make build-kernel
