name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build bootloader
      run: cargo build --target x86_64-unknown-uefi --bin boot
    - name: Build kernel
      run: RUSTFLAGS='-C link-arg=-Tsystem/core/src/linker.ld -C relocation-model=static' cargo build --target x86_64-unknown-none --bin core
